[global]
developmentMode = false

[server]
headless = true
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"